services:
  sql:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    platform: linux/arm64 
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: "Password@1"
    ports:
      - "1433:1433"